### ISSUE TITLE
nlua0 & new lpeg build dependency issue

### ISSUE THREAD

**Issue by PlumpMath** [nix-community/neovim-nightly-overlay#210]
Hello
I'm using gvolpe/neovim-flake 

https://github.com/gvolpe/neovim-flake/blob/main/flake.nix

issue information
https://github.com/neovim/neovim/issues/23905

Here is the (commit) build prior to encountering the error.
https://github.com/neovim/neovim/tree/7c8c1550737b34fabb3e4cecbc6b6bf3581b2235

Thanks.

**Comment by Kranzes** [comment]
Is this not #176 again?

**Comment by roblabla** [comment]
This occurs because `lpeg` is built as an MH_BUNDLE instead of an MH_DYLIB:

```
$ file /nix/store/l411mf169lrrrz9gkpn22ys8id0l06x9-luajit-2.1.0-2022-10-04-env/lib/lua/5.1/lpeg.so
/nix/store/l411mf169lrrrz9gkpn22ys8id0l06x9-luajit-2.1.0-2022-10-04-env/lib/lua/5.1/lpeg.so: Mach-O 64-bit bundle arm64
$ file /nix/store/l411mf169lrrrz9gkpn22ys8id0l06x9-luajit-2.1.0-2022-10-04-env/lib/libluajit-5.1.2.1.0.dylib
/nix/store/l411mf169lrrrz9gkpn22ys8id0l06x9-luajit-2.1.0-2022-10-04-env/lib/libluajit-5.1.2.1.0.dylib: Mach-O 64-bit dynamically linked shared library arm64
```

On macOS, you can't dynamically link an MH_BUNDLE, it can only get dlopen'd dynamically at runtime. Looking at the neovim source, it looks like they build lpeg *separately* from luajit. So we probably need to do the same thing here: build lpeg separately from luajit, and link against that.

**Comment by Kranzes** [comment]
Please move discussion to #176
