### ISSUE TITLE
No python provider

### ISSUE THREAD

**Issue by NilsIrl** [nix-community/neovim-nightly-overlay#70]
I installed and now get the following error whenever I do something in neovim making it unusable:

![image](https://user-images.githubusercontent.com/26231126/101991001-b2acc380-3ca1-11eb-994e-173da3a03e8b.png)

**Comment by mjlbach** [comment]
This shouldn't have anything to do with this overlay. If you're using home-manager, make sure
```
programs.neovim.withPython3 = true;
```

**Comment by NilsIrl** [comment]
I think the solution is to install `pkgs.neovim` instead of `pkgs.neovim-nightly`. So maybe the instructions in the README.md should be changed. I'm not exactly sure though, I'll need to double check.

**Comment by mjlbach** [comment]
That's not the solution, because pkgs.neovim will install neovim 0.4.4 from nixpkgs, pkgs.neovim-nightly will refer to the package added by the overlay. If you install either pkgs.neovim, or pkgs.neovim-nightly, without enabling the python provider in your configuration.nix or home.nix, you will get the error you posted.

**Comment by hurricanehrndz** [comment]
Anyway to do this with an install via nix-env -iA? I only ask because my home-manager config it not there yet.
