### ISSUE TITLE
Darwin build error for neovim-nightly package

### ISSUE THREAD

**Issue by c4dr01d** [nix-community/neovim-nightly-overlay#93]
Hi, I setup the overlay at my nix-darwin home profile and trying build it at my MacBook, but I got error:
```
a 'x86_64-linux' with features {} is required to build '/nix/store/mdldv8gwvcd5fkchncp90hmz3p9rcd99-builder.pl.drv', but I am a 'x86_64-darwin' with features {benchmark, big-parallel, nixos-test, recursive-nix}
```
Have any workaround or solution for this?

**Comment by mjlbach** [comment]
This doesn't seem like a neovim-nightly issue. FWIW I use this overlay on mac and linux.

**Comment by c4dr01d** [comment]
@mjlbach Emm..

**Comment by mjlbach** [comment]
Do you want to share the configuration.nix you are using for nix-darwin?

**Comment by c4dr01d** [comment]
@mjlbach https://github.com/c4dr01d/my-profile

**Comment by c4dr01d** [comment]
@mjlbach Is on modules/programs/neovim.nix, import at profiles/c4droid/default.nix

**Comment by mjlbach** [comment]
Nothing looks incorrect at first glance, I would have someone take a look at your profile on IRC, because neovim-nightly is just a standard overlay, so whatever problem you're having is unlikely to be unique to this overlay.

A test you can do is removing neovim-nightly and seeing if the problem still occurs, or trying to use another overlay and also seeing if you get the issue.

**Comment by c4dr01d** [comment]
@mjlbach I think my profile not problem, maybe is the nix-daemon configuration question..

**Comment by c4dr01d** [comment]
@mjlbach I was test some overlay, they can bulit on darwin, only neovim cannot.

**Comment by mjlbach** [comment]
I can't go through your flake unfortunately, I would imagine the issue is somewhere in how you're importing the overlay here: https://github.com/c4dr01d/my-profile/blob/f9100e4a072bd7d48d627c12536c3b7d96cd47b6/flake.nix#L49-L76

Maybe something to do with how you're using flake-utils.

Here's my system flake. https://github.com/mjlbach/nix-dotfiles/blob/bfa61c9d856ae3592e64b25cfb6fc347840b513e/nixpkgs/flake.nix#L38-L72

**Comment by c4dr01d** [comment]
@mjlbach I'll trying rewrite my flake.nix later, thanks for your hint.
